### ISSUE TITLE
Quick question.

### ISSUE THREAD

**Issue by Ibbanez** [einsteinx2/gditools#1]
Sorry, I couldn't find this answer anywhere. I recently ran this on all my titles, and one thing I noticed was that during the process, it converted all the .bin files to .iso, and added an extra .iso file.  Is this the normal process to swap them to .iso?  I just wanted to make sure while I wait on my GDEMU to arrive.  Now I tested in various emulators, and they were fine, its just I didn't see this mentioned anywhere online, so i wanted to double check first.  Thanks.

**Comment by einsteinx2** [comment]
Hi sorry, just saw this. The only work I did on this is to expose the gdishrink functionality that is in the script and run it against my GDI files. I just checked my SD card and I do see that all of my shrunk games have ISO files rather than BIN files (though I don't have the originals to easily check right now), so I think what you see is normal. All shrunk games have worked perfectly for me on my GDEMU.
